name: Build – Windows ARM64 (Tauri)

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-windows-arm64:
    runs-on: windows-latest

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install JS deps
        run: pnpm ci

      - name: Setup Rust (stable) + ARM64 target
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-pc-windows-msvc

      - name: Cache Rust build
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            src-tauri -> target

      # Build the Tauri app for Windows ARM64
      - name: Build (tauri v2) – aarch64
        run: pnpm tauri build

      - name: Upload bundles
        uses: actions/upload-artifact@v4
        with:
          name: quick-access-app-windows-arm64
          path: |
            src-tauri/target/aarch64-pc-windows-msvc/release/bundle/**/*

      # (Optional) also upload the raw exe if you produce one
      - name: Upload raw exe (optional)
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: quick-access-app-exe-windows-arm64
          path: |
            src-tauri/target/aarch64-pc-windows-msvc/release/*.exe
          if-no-files-found: ignore
